#!/usr/bin/env bash
# Start the CAD Viewer the way the shipped skill tells a user to, and check it answers.
#
# Every other check asks whether the bundle is correctly ASSEMBLED. bundle.sh --check compares
# generated bytes; check-builds.sh inspects the layout. Neither runs it. `npm start` was declared
# in the runtime's package.json, shipped without its launcher, and stayed broken from 0.4.0 to
# 0.4.18 because no test ever executed the one command the skill documents.
#
# The command below is that command. Keep it identical to the one in
# skills/cad-viewer/SKILL.md; if the doc changes, this changes with it.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
VIEWER_DIR="${VIEWER_RUNTIME_DIR:-$REPO_ROOT/skills/cad-viewer/scripts/viewer}"
PORT="${VIEWER_LAUNCH_PORT:-3299}"
HOST="127.0.0.1"

echo "==> CAD Viewer launch smoke test (runtime: $VIEWER_DIR)"

# The launcher has to be present before anything else is worth trying: its absence is the exact
# regression this guards, and it fails as a missing module rather than as a bad server.
for required in package.json scripts/start-viewer.mjs; do
  if [ ! -f "$VIEWER_DIR/$required" ]; then
    echo "FAIL: the runtime is missing $required" >&2
    echo "      npm start cannot work without it; check build_runtime in" >&2
    echo "      scripts/bundle/skills/bundle-cad-viewer.sh" >&2
    exit 1
  fi
done

log="$(mktemp)"
npm --prefix "$VIEWER_DIR" run start -- --host "$HOST" --port "$PORT" > "$log" 2>&1 &
launcher_pid=$!

cleanup() {
  # Job control announces the terminated background job on stderr, which reads like a failure
  # in CI logs right after a pass. Turn it off before killing anything.
  set +m
  kill "$launcher_pid" 2>/dev/null || true
  pkill -P "$launcher_pid" 2>/dev/null || true
  # The launcher spawns the backend as a child process, so killing the shim alone can leave the
  # port held and fail the next run for a reason that has nothing to do with the next run.
  pkill -f "server_py.(server|start_viewer).*--port $PORT" 2>/dev/null || true
  wait "$launcher_pid" 2>/dev/null || true
}
trap cleanup EXIT

status=""
for _ in $(seq 1 30); do
  status="$(curl -s -o /dev/null -m 3 -w '%{http_code}' "http://$HOST:$PORT/" || true)"
  [ "$status" = "200" ] && break
  if ! kill -0 "$launcher_pid" 2>/dev/null; then
    echo "FAIL: the launcher exited before serving" >&2
    sed 's/^/    /' "$log" >&2
    exit 1
  fi
  sleep 1
done

if [ "$status" != "200" ]; then
  echo "FAIL: no 200 from http://$HOST:$PORT/ (last status: ${status:-none})" >&2
  sed 's/^/    /' "$log" >&2
  exit 1
fi

# The front end alone is not proof: `start` serves a prebuilt bundle, so a live page with a dead
# CAD API still looks fine in a browser until the first model load.
api="$(curl -s -o /dev/null -m 3 -w '%{http_code}' "http://$HOST:$PORT/__cad/server" || true)"
if [ "$api" != "200" ]; then
  echo "FAIL: the page served but /__cad/server returned ${api:-none}" >&2
  sed 's/^/    /' "$log" >&2
  exit 1
fi

echo "    served / and /__cad/server on port $PORT"
echo "==> CAD Viewer launch smoke test passed"
